#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

ts="$(date +%Y%m%d_%H%M%S)"
backup_dir="_migrated/fix_tripcom_exports_${ts}"
mkdir -p "$backup_dir"

f="src/travel_tracker/sources/flights/tripcom.py"
mkdir -p "$(dirname "$f")"

if [ -f "$f" ]; then
  cp "$f" "$backup_dir/tripcom.py.bak"
  echo "[OK] backup: $backup_dir/tripcom.py.bak"
fi

cat > "$f" <<'PY'
from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


@dataclass(frozen=True)
class TripcomRoute:
    route_id: str
    origin: str
    destination: str
    url: str


def load_tripcom_routes(config_path: str = "config/flights_tripcom_routes.json") -> list[TripcomRoute]:
    """
    Read routes generated by ./scripts/one_click_gen_tripcom_flights_20cities.sh
    Expected JSON: list[{route_id, origin, destination, url, ...}]
    """
    p = Path(config_path)
    if not p.exists():
        raise FileNotFoundError(f"routes config not found: {p}")

    raw = json.loads(p.read_text(encoding="utf-8"))
    if isinstance(raw, dict) and "routes" in raw:
        raw = raw["routes"]
    if not isinstance(raw, list):
        raise ValueError("routes json must be a list (or dict with 'routes' list)")

    out: list[TripcomRoute] = []
    for x in raw:
        if not isinstance(x, dict):
            continue
        rid = (x.get("route_id") or x.get("id") or "").strip()
        o = (x.get("origin") or "").strip().upper()
        d = (x.get("destination") or "").strip().upper()
        url = (x.get("url") or "").strip()
        if not (rid and o and d and url):
            continue
        out.append(TripcomRoute(route_id=rid, origin=o, destination=d, url=url))

    return out


def fetch_route_html(*, client, url: str, raw_path: Path) -> bytes:
    """
    Fetch HTML for a trip.com route page.
    - Uses PoliteHttpClient.get(url)
    - If TRAVEL_FLIGHTS_USE_PW=1, http_client.get() is already patched to use Playwright for trip.com
    """
    raw_path.parent.mkdir(parents=True, exist_ok=True)
    resp = client.get(url)
    body = resp.body or b""
    raw_path.write_bytes(body)
    return body
PY

echo "[OK] wrote: $f"

echo ""
echo "[VERIFY] import smoke test:"
poetry run python - <<'PY'
from travel_tracker.sources.flights.tripcom import load_tripcom_routes, fetch_route_html
routes = load_tripcom_routes("config/flights_tripcom_routes.json")
print("[OK] imported load_tripcom_routes/fetch_route_html, routes=", len(routes))
print("sample:", [(r.route_id, r.origin, r.destination) for r in routes[:5]])
PY

echo ""
echo "[NEXT] Run (first 3 routes, PW on):"
echo 'TRAVEL_FLIGHTS_USE_PW=1 TRAVEL_FLIGHTS_MAX_ROUTES=3 TRAVEL_TIMEOUT=12 TRAVEL_RETRIES=0 poetry run python -m travel_tracker.flights_main --force'
